### ISSUE TITLE
Is this still needed?

### ISSUE THREAD

**Issue by pcav** [JuergenWeichand/qgis-wfs20-client-plugin#10]
AFAIK WFS is supported in recent QGIS. Please correct me if I'm wrong.

**Comment by JuergenWeichand** [comment]
>  Is this still needed?
Yes. 

According to https://github.com/qgis/QGIS-Enhancement-Proposals/issues/53 there is no support of stored queries yet.

Also some strict WFS are not useable because of https://hub.qgis.org/issues/14685

**Comment by pcav** [comment]
Thanks. Perhaps it would be useful to add a note to the About, for the users to understand when it is useful to install the plugin.
BTW, please consider contributing direclty to the core funcionality.
All the best.
